name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Setup Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # Step 3: Install dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8

    # Step 4: Lint code
    - name: Lint code
      run: flake8 .

    # Step 5: Build Docker image
    - name: Build Docker image
      run: docker build -t housing-fastapi .

    # Step 6: Log in to DockerHub
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 7: Push Docker image to DockerHub
    - name: Push Docker image
      run: |
        docker tag housing-fastapi ${{ secrets.DOCKER_USERNAME }}/housing-fastapi:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/housing-fastapi:latest
